### ISSUE TITLE
请问CFG Lock是怎么弄的

### ISSUE THREAD

**Issue by sh0w1ov3** [michelle0812/DELL-OptiPlex-7090-11700-RX570#1]
RT

**Comment by michelle0812** [comment]
利用CFGLOCK.efi解鎖MSR 0xE2
https://blog.daliansky.net/undefined.html

**Comment by sh0w1ov3** [comment]
Dell T3660 13900 ddr5
貌似这新版的dell bios不支持cfglock.efi ，提示
Brumbaers CFG Unlock
Couldn't find any Variable with cfg in name
The End. Press a key

**Comment by michelle0812** [comment]
1. [UniversalIFR-Extractor](https://github.com/LongSoft/Universal-IFR-Extractor)：請下載[ifrextract_v0.3.6.osx.zip](https://github.com/LongSoft/Universal-IFR-Extractor/releases/download/v0.3.6/ifrextract_v0.3.6.osx.zip)。BIOS的訊息轉化成文字的工具軟體
2. [grub-mod-setup_var](https://github.com/datasone/grub-mod-setup_var)：下載[modGRUBShell.efi](https://github.com/datasone/grub-mod-setup_var/releases/download/1.0/modGRUBShell.efi)這個修改過GRUB sdell檔案。
step1.用第一套工具去找到 cfg-lock的位置
step2.用第二套工具去設定cfg-lock  disable. 
我印象中是這樣操作的，很困難但學會了很難得

資料來源: https://www.imacpc.net/archives/1888

**Comment by sh0w1ov3** [comment]
这个bios提取出来 获取不到cfg的值



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: michelle0812 ***@***.***&gt;
发送时间: 2023年5月17日 14:20
收件人: mejss ***@***.***&gt;
主题: Re: [michelle0812/DELL-OptiPlex-7090-11700-RX570] 请问CFG Lock是怎么弄的 (Issue #1)





  
UniversalIFR-Extractor：請下載ifrextract_v0.3.6.osx.zip。BIOS的訊息轉化成文字的工具軟體
 
grub-mod-setup_var：下載modGRUBShell.efi這個修改過GRUB sdell檔案。
 step1.用第一套工具去找到 cfg-lock的位置
 step2.用第二套工具去設定cfg-lock  disable.
 我印象中是這樣操作的，很困難但學會了很難得

**Comment by michelle0812** [comment]
多多嘗試，不要放棄

**Comment by sh0w1ov3** [comment]
放弃了，在Windows或pe里 使用bios备份工具提示无法识别bios

使用Dell_PFS_Extract.py转换官网bios固件再ifrextractor提示 `No IFR data found`

**Comment by michelle0812** [comment]
不要放棄，過幾天再試試看

**Comment by CaptainGod** [comment]
请问解锁这个机器CFG Lock的方法找到了吗？谢谢！

**Comment by sh0w1ov3** [comment]
> 请问解锁这个机器CFG Lock的方法找到了吗？谢谢！

未果

**Comment by CaptainGod** [comment]
> > 请问解锁这个机器CFG Lock的方法找到了吗？谢谢！
> 
> 未果

谢谢回复，我根据网络上的教程提取到了7090的信息，解锁了CFG Lock，请参考：
Dell Optiplex解锁CFG Lock：

VarStoreId: 0x3
VarOffset: 0x43
Name: "CpuSetup"

使用GRUB Shell解锁的命令:
setup_var_cv CpuSetup 0x43 0x01 0x00

**Comment by sh0w1ov3** [comment]
> > > 请问解锁这个机器CFG Lock的方法找到了吗？谢谢！
> > 
> > 
> > 未果
> 
> 谢谢回复，我根据网络上的教程提取到了7090的信息，解锁了CFG Lock，请参考： Dell Optiplex解锁CFG Lock：
> 
> VarStoreId: 0x3 VarOffset: 0x43 Name: "CpuSetup"
> 
> 使用GRUB Shell解锁的命令: setup_var_cv CpuSetup 0x43 0x01 0x00

牛批，有空我测试验证一下

**Comment by CaptainGod** [comment]
# 参考教程：

- https://github.com/dreamwhite/bios-extraction-guide/blob/master/README.md#unlock-cfg-lock
- [https://sumingyd.github.io/OpenCore-Post-Install/misc/msr-lock.html#手动关闭cfg-lock](https://sumingyd.github.io/OpenCore-Post-Install/misc/msr-lock.html#%E6%89%8B%E5%8A%A8%E5%85%B3%E9%97%ADcfg-lock)

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年11月16日 19:17 |
| 收件人 | michelle0812/DELL-OptiPlex-7090-11700-RX570 ***@***.***> |
| 抄送人 | CaptainGod ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [michelle0812/DELL-OptiPlex-7090-11700-RX570] 请问CFG Lock是怎么弄的 (Issue #1) |

Closed #1 as completed.
